@startuml

title 时序图
skinparam defaultFontName 宋体

== 游戏初始化 ==
Map -> Map : 初始化地图属性
Snake -> Map : 基于地图初始化蛇的位置
Food -> Map : 基于地图初始化食物位置
note left
    尝试左右时序图
    游戏触发条件
    加上loop循环的时序
end note

== 开始游戏 ==
Snake -> Food : 蛇吃到食物，增加体型
Food -> Map : 刷新新的食物位置

== 结束游戏 ==
Snake -> Map : 成功或者失败结束游戏
@enduml